name: Build and Commit APK

on:
  push:
    branches:
      - main
    paths:
      - 'manifest.gradle'
  workflow_dispatch:
jobs:
  check-and-publish:
    env:
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check if sample-app version changed
        id: check_sample_app
        run: |
          PREV_COMMIT=$(git rev-parse HEAD^)
          OLD_LINE=$(git show $PREV_COMMIT:manifest.gradle | grep '"sample-app"')
          NEW_LINE=$(grep '"sample-app"' manifest.gradle)
          echo "Old: $OLD_LINE"
          echo "New: $NEW_LINE"
          if [ "$OLD_LINE" != "$NEW_LINE" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Configure signature
        if: steps.check_sample_app.outputs.changed == 'true'
        run: |
          mkdir -p $HOME/.android
          echo "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 -d > $HOME/.android/debug.keystore
      - name: Grant execute permission for gradlew
        if: steps.check_sample_app.outputs.changed == 'true'
        run: chmod +x ./gradlew

      - name: Build release APK
        if: steps.check_sample_app.outputs.changed == 'true'
        run: ./gradlew generateReleaseApk

      - name: Commit generated sample-app/release artifacts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sample-app/release/*
          git commit -m "Update sample apk" || echo "No changes to commit"
          git push